---
driver:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh:
    forward_agent: true

platforms:
- name: fedora-19-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
    region: Amsterdam 2

- name: fedora-20-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
    region: Amsterdam 2

- name: ubuntu-10-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
    region: Amsterdam 2
  run_list:
  - recipe[apt]

- name: ubuntu-12-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
    region: Amsterdam 2
  run_list:
  - recipe[apt]

- name: ubuntu-14-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
    region: Amsterdam 2
  run_list:
  - recipe[apt]
