---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 64738, host: 64738, auto_correct: true}]

provisioner:
  require_chef_omnibus: true

platforms:
- name: debian-6.0.10
  run_list: recipe[apt]
- name: debian-7.6
  run_list: recipe[apt]
- name: fedora-19
  driver_config:
    box: opscode-fedora-19
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_fedora-19_chef-provisionerless.box
- name: fedora-20
- name: ubuntu-10.04
  run_list: recipe[apt]
- name: ubuntu-12.04
  run_list: recipe[apt]
- name: ubuntu-14.04
  run_list: recipe[apt]
- name: ubuntu-15.04
  run_list: recipe[apt]

suites:
- name: default
  run_list:
  - recipe[mumble_server_test::default]
- name: runit
  excludes:
  - fedora-19
  - fedora-20
  run_list:
  - recipe[mumble_server_test::default]
  attributes:
    mumble_server:
      service_type: runit_service
