---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 64738, host: 64738, auto_correct: true}]

provisioner:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: debian-6.0.10
  run_list:
  - recipe[apt]
- name: debian-7.6
  run_list:
  - recipe[apt]
- name: fedora-18
- name: fedora-19
- name: fedora-20

suites:
- name: default
  run_list:
  - recipe[mumble_server_test::default]
- name: runit
  excludes:
  - fedora-18
  - fedora-19
  - fedora-20
  run_list:
  - recipe[mumble_server_test::default]
  attributes:
    mumble_server:
      service_type: runit_service
